### ISSUE TITLE
What Happened?

### ISSUE THREAD

**Issue by lanaschuhmacher** [unixstickers/foss-swag-designs#1]
Hi, what happened with [Unixstickers](https://www.unixstickers.com)? Did [Sticker Mule](https://www.stickermule.com/unlock?ref_id=2743880701) buy it? 🤔

**Comment by Facens** [comment]
Hi @lanaschuhmacher, Unixstickers has joined Sticker Mule a while ago and has been an integral part of the team for a while now!
